#!/usr/bin/env bash
#
# setup-tunnel.sh — Setup Cloudflare Tunnel untuk helpdeskit.biz.id
#
# Script ini akan:
#   1. Membuat service token di Cloudflare (jika belum ada)
#   2. Membuat file konfigurasi tunnel
#   3. Membuat systemd service untuk cloudflared
#   4. Memulai tunnel
#
# Pastikan Anda sudah login ke Cloudflare dashboard sebelum menjalankan script ini.
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLOUDFLARED_DIR="$HOME/.cloudflared"
DOMAIN="helpdeskit.biz.id"
TUNNEL_NAME="helpdeskit-tunnel"
LOCAL_PORT="${1:-8000}"

echo "=========================================="
echo "  Cloudflare Tunnel Setup"
echo "  Domain: $DOMAIN"
echo "  Local Port: $LOCAL_PORT"
echo "=========================================="

# -------------------------------------------------------
# 0. Pastikan cloudflared terinstal
# -------------------------------------------------------
if ! command -v cloudflared &>/dev/null; then
    echo "[ERROR] cloudflared tidak ditemukan. Install dulu:"
    echo "  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb"
    echo "  sudo dpkg -i cloudflared.deb"
    exit 1
fi

echo "[OK] cloudflared ditemukan: $(cloudflared --version)"

# -------------------------------------------------------
# 1. Buat direktori konfigurasi
# -------------------------------------------------------
mkdir -p "$CLOUDFLARED_DIR"
echo "[OK] Direktori konfigurasi: $CLOUDFLARED_DIR"

# -------------------------------------------------------
# 2. Login ke Cloudflare (buka browser)
# -------------------------------------------------------
echo ""
echo "[STEP 1] Login ke Cloudflare..."
echo "Browser akan terbuka, login ke akun Cloudflare Anda."
echo "Setelah selesai, tekan Enter di terminal ini."
read -rp "Tekan Enter setelah login selesai..." _

cloudflared tunnel login

# -------------------------------------------------------
# 3. Buat tunnel
# -------------------------------------------------------
echo ""
echo "[STEP 2] Membuat tunnel: $TUNNEL_NAME"
cloudflared tunnel create "$TUNNEL_NAME"

# Dapatkan tunnel UUID
TUNNEL_UUID=$(cloudflared tunnel list --output json 2>/dev/null | \
    python3 -c "import sys,json; data=json.load(sys.stdin); print([t['id'] for t in data if t['name']=='$TUNNEL_NAME'][0])" 2>/dev/null || \
    echo "")

if [ -z "$TUNNEL_UUID" ]; then
    echo "[ERROR] Gagal mendapatkan tunnel UUID"
    echo "Cek di: https://dash.cloudflare.com/ -> Zero Trust -> Access -> Tunnels"
    exit 1
fi

echo "[OK] Tunnel UUID: $TUNNEL_UUID"

# -------------------------------------------------------
# 4. Buat file konfigurasi tunnel
# -------------------------------------------------------
echo ""
echo "[STEP 3] Membuat file konfigurasi tunnel..."

cat > "$CLOUDFLARED_DIR/config.yml" <<EOF
# Cloudflare Tunnel Configuration
# Domain: $DOMAIN
# Generated by setup-tunnel.sh

tunnel: $TUNNEL_UUID
credentials-file: $CLOUDFLARED_DIR/$TUNNEL_UUID.json

ingress:
  # Route utama ke aplikasi Helpdesk
  - hostname: $DOMAIN
    service: http://localhost:$LOCAL_PORT

  # Route www
  - hostname: www.$DOMAIN
    service: http://localhost:$LOCAL_PORT

  # API endpoint (jika ada)
  - hostname: api.$DOMAIN
    service: http://localhost:5005

  # Catch-all (matikan jika tidak diperlukan)
  - service: http_status:404

# Cloudflare Tunnel settings
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/
EOF

echo "[OK] Config file: $CLOUDFLARED_DIR/config.yml"

# -------------------------------------------------------
# 5. Buat systemd service
# -------------------------------------------------------
echo ""
echo "[STEP 4] Membuat systemd service..."

SERVICE_FILE="/etc/systemd/system/cloudflared@$TUNNEL_NAME.service"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=Cloudflare Tunnel ($TUNNEL_NAME)
After=network.target

[Service]
Type=simple
User=$USER
ExecStart=/usr/local/bin/cloudflared tunnel --config $CLOUDFLARED_DIR/config.yml run $TUNNEL_UUID
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

echo "[OK] Service file: $SERVICE_FILE"

# -------------------------------------------------------
# 6. Aktifkan dan start service
# -------------------------------------------------------
echo ""
echo "[STEP 5] Mengaktifkan dan memulai service..."

sudo systemctl daemon-reload
sudo systemctl enable "cloudflared@$TUNNEL_NAME"
sudo systemctl start "cloudflared@$TUNNEL_NAME"

sleep 2

# Cek status
if sudo systemctl is-active --quiet "cloudflared@$TUNNEL_NAME"; then
    echo "[OK] Service cloudflared berjalan!"
else
    echo "[WARN] Service mungkin belum siap. Cek log:"
    echo "  sudo journalctl -u cloudflared@$TUNNEL_NAME -f"
fi

# -------------------------------------------------------
# 7. Cek status tunnel
# -------------------------------------------------------
echo ""
echo "[STEP 6] Memeriksa status tunnel..."
cloudflared tunnel list

echo ""
echo "=========================================="
echo "  Setup selesai!"
echo "=========================================="
echo ""
echo "Langkah berikutnya:"
echo "  1. Pastikan aplikasi Helpdesk berjalan di port $LOCAL_PORT"
echo "     (jalankan: ./start.sh)"
echo "  2. Buka https://$DOMAIN di browser"
echo "  3. Jika belum muncul, cek DNS di Cloudflare dashboard"
echo "     dan pastikan ada record CNAME untuk $DOMAIN -> $TUNNEL_UUID.cfargotunnel.com"
echo ""
echo "Untuk melihat log tunnel:"
echo "  sudo journalctl -u cloudflared@$TUNNEL_NAME -f"
echo ""
echo "Untuk menghentikan tunnel:"
echo "  sudo systemctl stop cloudflared@$TUNNEL_NAME"
